# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexImage',
            fields=[
                ('source', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('fid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('rank', models.IntegerField()),
                ('point', models.IntegerField()),
                ('university', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=30)),
            ],
        ),
    ]
