# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=30, verbose_name='所在大学')),
                ('institute', models.CharField(max_length=30, verbose_name='所在学校')),
                ('course', models.CharField(max_length=30, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryFile',
            fields=[
                ('fhash', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='文件哈希值')),
                ('uid', models.IntegerField(verbose_name='上传者Uid')),
                ('university', models.CharField(max_length=30, verbose_name='所在大学')),
                ('institute', models.CharField(max_length=30, verbose_name='所在学院')),
                ('course', models.CharField(max_length=30, verbose_name='所属课程')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('introduction', models.CharField(max_length=200, verbose_name='简介')),
                ('filetype', models.CharField(max_length=10, verbose_name='文件类型')),
                ('extension', models.CharField(max_length=10, verbose_name='文件扩展名')),
                ('uploadtime', models.DateTimeField(verbose_name='上传时间')),
                ('filesize', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='文件大小')),
                ('pagecnt', models.IntegerField(verbose_name='文件页数')),
                ('downloadcnt', models.IntegerField(verbose_name='下载次数')),
            ],
        ),
        migrations.CreateModel(
            name='PendingFile',
            fields=[
                ('fhash', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='文件哈希值')),
                ('uid', models.IntegerField(verbose_name='上传者Uid')),
                ('university', models.CharField(max_length=30, verbose_name='所在大学')),
                ('institute', models.CharField(max_length=30, verbose_name='所在学院')),
                ('course', models.CharField(max_length=30, verbose_name='所属课程')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('introduction', models.CharField(max_length=200, verbose_name='简介')),
                ('filetype', models.CharField(max_length=10, verbose_name='文件类型')),
                ('extension', models.CharField(max_length=10, verbose_name='文件扩展名')),
                ('uploadtime', models.DateTimeField(verbose_name='上传时间')),
                ('filesize', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='文件大小')),
                ('pagecnt', models.IntegerField(verbose_name='文件页数')),
            ],
        ),
        migrations.AlterField(
            model_name='indeximage',
            name='destination',
            field=models.CharField(max_length=200, verbose_name='广告指向地址'),
        ),
        migrations.AlterField(
            model_name='indeximage',
            name='source',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='图片来源'),
        ),
        migrations.AlterField(
            model_name='mycollection',
            name='fid',
            field=models.IntegerField(verbose_name='Fid'),
        ),
        migrations.AlterField(
            model_name='mycollection',
            name='uid',
            field=models.IntegerField(verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.CharField(max_length=30, verbose_name='所在学院'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(max_length=30, verbose_name='所在大学'),
        ),
    ]
