# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0002_auto_20161202_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='Uid')),
                ('fid', models.IntegerField(verbose_name='Fid')),
            ],
        ),
    ]
