# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0003_myuploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryfile',
            name='fid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='文件Fid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingfile',
            name='fid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='文件Fid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libraryfile',
            name='fhash',
            field=models.CharField(max_length=50, verbose_name='文件哈希值'),
        ),
        migrations.AlterField(
            model_name='pendingfile',
            name='fhash',
            field=models.CharField(max_length=50, verbose_name='文件哈希值'),
        ),
    ]
