# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0004_auto_20161204_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryfile',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
            preserve_default=False,
        ),
    ]
