# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform', '0006_libraryfile_isfavourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='institute',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='university',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='indeximage',
            old_name='source',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='indeximage',
            old_name='destination',
            new_name='onclickUrl',
        ),
        migrations.RenameField(
            model_name='libraryfile',
            old_name='introduction',
            new_name='brief',
        ),
        migrations.RenameField(
            model_name='libraryfile',
            old_name='institute',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='libraryfile',
            old_name='downloadcnt',
            new_name='download',
        ),
        migrations.RenameField(
            model_name='libraryfile',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='libraryfile',
            old_name='pagecnt',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='libraryfile',
            old_name='university',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='libraryfile',
            old_name='filesize',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='pendingfile',
            old_name='introduction',
            new_name='brief',
        ),
        migrations.RenameField(
            model_name='pendingfile',
            old_name='institute',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='pendingfile',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pendingfile',
            old_name='pagecnt',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='pendingfile',
            old_name='university',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='pendingfile',
            old_name='filesize',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='institute',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rank',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='university',
            new_name='school',
        ),
    ]
